### ISSUE TITLE
BME280 does not react on I2C

### ISSUE THREAD

**Issue by Miq1** [technoblogy/tiny-bme280#1]
Hi,

I am trying to use the tiny-bme230 lib on an ATtiny85 with the TinyWireM library, as the standard Wire library is consuming too many resources. I changed the #include <Wire.h> to #include <TinyWireM.h> and put a #define Wire TinyWireM after it.

The sketch compiles without problems, but when running on the ATtiny, no movement is to be seen on the I2C lines. Just the start signal is visible and nothing thereafter.

What could be the problem?

**Comment by technoblogy** [comment]
Try putting pullups on the I2C lines. I read that the TinyWireM library requires them. If that doesn't help I'll think again!

**Comment by Miq1** [comment]
Well, I in fact do have 10k pullups on both SDA and SCL lines... ;)

**Comment by Miq1** [comment]
I found it - my BME280 has a different I2C address - 0x76 as compared to the default 0x77.

Thanks anyway!
