### ISSUE TITLE
Adding altitude readings

### ISSUE THREAD

**Issue by Akegata** [technoblogy/tiny-bme280#2]
Hi!

I would like to use this library to make an altimeter, but that would of course require altitude readings. Would you consider adding that to the library?
If I was better at coding C I would happily add it myself. :s

**Comment by technoblogy** [comment]
I'll look at what's involved. I think my main problem would be how to test it.

**Comment by Akegata** [comment]
I would be able to test it for you.
I have the altimeter built on an Arduino that's thoroughly tested both in the sky and a jury-rigged pressure chamber I have at home. I plan on using both options to test an attiny85 version. :)

**Comment by technoblogy** [comment]
I've had a look at the code and I think it's just:

````
// Altitude in metres
float BME280altitude (float referencePressure) {
  return ((float)-45846.2)*(pow(((float)BME280pressure()/(float)referencePressure), 0.190263) - (float)1);
}
````
where I think **referencePressure** is the pressure in Pa at zero altitude; for example, 101325.0. Unfortunately this needs floats, unlike the rest of my tiny-bme280 library, so I'm not sure there's much point incorporating it, unless you can see a way of getting reasonable accuracy without needing floats.
