### ISSUE TITLE
BME280setI2Caddress(address)

### ISSUE THREAD

**Issue by mmr1234** [technoblogy/tiny-bme280#4]
I am trying to use your library for a ATTINY85 project.  My BME280 has a I2C address of 0x76.

What should the BME280setI2Caddress(address) code look like?

I am using SpenceKonde ATTinycore.

Many thanks for any assistance.

**Comment by technoblogy** [comment]
BME280setI2Caddress(0x76);

**Comment by mmr1234** [comment]
Many thanks for the clarification
