### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mateorotim** [technoblogy/tiny-bme280#5]
When I use your library i can't compile my project, something to do with the Wire.h library I think.
Here is the board profile that I'm using and the error:

![board](https://user-images.githubusercontent.com/13685981/69636783-a7b3d080-1057-11ea-9bcf-19a7cf1e9883.png)

Error:

`Arduino: 1.8.10 (Windows 10), Board: "ATtiny25/45/85, ATtiny85, Internal 8 MHz"

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\utility\twi.c: In function 'twi_init':

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\utility\twi.c:76:16: error: 'SDA' undeclared (first use in this function)

   digitalWrite(SDA, 1);

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\utility\twi.c:76:16: note: each undeclared identifier is reported only once for each function it appears in

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\utility\twi.c:77:16: error: 'SCL' undeclared (first use in this function); did you mean 'SPL'?

   digitalWrite(SCL, 1);

(lines deleted)

**Comment by technoblogy** [comment]
What core are you using for the ATtiny85?

**Comment by technoblogy** [comment]
I think the errors are due to the fact that you don't have an ATtiny85 Wire library. See this post:

[ATtiny85 Weather Station](http://www.plasticki.com/show?2F5D)

You need to use Spence Konde's ATTiny Core which has a special version of the Wire library for the ATtiny85.

**Comment by mateorotim** [comment]
Yes I'm using different core, I saw your post, just didn't see the part where you specify the core, sorry and thanks!
